sections:
  general:
    display: General
    fields:
      - handle: section_general
        field:
          type: section
          listable: hidden
          display: "Configurari generale"
          instructions: "Opțiuni de configurare globală a site-ului."
      - handle: phone_number
        field:
          input_type: text
          antlers: false
          display: "Telefon contact"
          type: text
          icon: text
          instructions: "Telefon contact clinica"
          width: 50
          listable: hidden
          instructions_position: above
      - handle: email_address
        field:
          input_type: email
          antlers: false
          display: "Email contact"
          type: text
          icon: text
          instructions: "Email contact clinica"
          width: 50
          listable: hidden
          instructions_position: above
          validate:
            - email
      - handle: copyright_since
        field:
          placeholder: "2020"
          input_type: number
          character_limit: 4
          prepend: ©
          antlers: false
          default: "2020"
          display: "Copyright since"
          instructions: "The website will add ` - current_year ` if they differ."
          type: text
          icon: text
          width: 50
          listable: hidden
          instructions_position: above
          validate:
            - required
      - handle: copyright_name
        field:
          input_type: text
          antlers: false
          display: "Nume drept de autor"
          type: text
          icon: text
          instructions: "Returneaza nume website"
          width: 50
          listable: hidden
          instructions_position: above
  error_messages:
    display: "Mesaje eroare"
    fields:
      - handle: section_404
        field:
          type: section
          listable: hidden
          display: "404 error"
      - import: error_message
        prefix: "404_"
