title: Services
sections:
  main:
    display: Main
    fields:
      - handle: title
        field:
          type: text
          required: true
          input_type: text
          antlers: false
          display: Title
          icon: text
          listable: hidden
          instructions_position: above
          validate:
            - required
      - handle: excerpt
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
          display: Excerpt
          type: markdown
          icon: markdown
          listable: hidden
          instructions_position: above
          validate:
            - required
      - handle: imagine
        field: figure.image
        config:
          display: Imagine
      - import: page_builder
  sidebar:
    display: Sidebar
    fields:
      - handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
      - handle: parent
        field:
          type: entries
          collections:
            - pages
          max_items: 1
          listable: false
          localizable: true
